resilience4j:
    metrics: false
    endpoints:
        circuitBreakers:
            enabled: true
            path: circuitbreaker
            eventConsumerBufferSize: 100
        rateLimiters:
            enabled: true
            path: ratelimiter
            eventConsumerBufferSize: 100
        retries:
            enabled: true
            path: retry
            eventConsumerBufferSize: 100
        bulkheads:
            enabled: true
            path: bulkhead
            eventConsumerBufferSize: 100
    circuitBreaker:
        configs:
            default:
                ringBufferSizeInClosedState: 200
                ringBufferSizeInHalfOpenState: 20
                waitDurationInOpenStateMillis: 1000
                failureRateThreshold: 60
                automaticTransitionFromOpenToHalfOpenEnabled: true
                recordExceptions:
                    - resilience4j.ratpack.App$DummyException1
                    - resilience4j.ratpack.App$DummyException2
            shared:
                ringBufferSizeInClosedState: 200
                ringBufferSizeInHalfOpenState: 20
                waitDurationInOpenStateMillis: 1000
                failureRateThreshold: 60
                automaticTransitionFromOpenToHalfOpenEnabled: true
                recordExceptions:
                    - resilience4j.ratpack.App$DummyException1
                    - resilience4j.ratpack.App$DummyException2
        instances:
            test1:
                baseConfig: default
                ringBufferSizeInClosedState: 100
            test2:
                ringBufferSizeInClosedState: 200
                ringBufferSizeInHalfOpenState: 20
                waitDurationInOpenState: PT5S
                failureRateThreshold: 60
                automaticTransitionFromOpenToHalfOpenEnabled: true
                recordExceptions:
                    - resilience4j.ratpack.App$DummyException1
    rateLimiter:
        configs:
            default:
                limitForPeriod: 100
                limitRefreshPeriodInNanos: 900
                timeoutInMillis: 10
            shared:
                limitForPeriod: 100
                limitRefreshPeriodInNanos: 900
                timeoutInMillis: 10
        instances:
            test1:
                baseConfig: default
                limitForPeriod: 150
            test2:
                limitForPeriod: 100
                limitRefreshPeriod: PT0.0000009S
                timeoutDuration: PT0.010S
    retry:
        configs:
            default:
                maxRetryAttempts: 3
                waitDurationInMillis: 1000
            shared:
                maxRetryAttempts: 3
                waitDurationInMillis: 1000
        instances:
            test1:
                baseConfig: default
                maxRetryAttempts: 4
            test2:
                maxRetryAttempts: 3
                waitDuration: PT1S
    bulkhead:
        configs:
            default:
                maxConcurrentCalls: 50
                maxWaitTime: 500
            shared:
                maxConcurrentCalls: 50
                maxWaitTime: 500
        instances:
            test1:
                baseConfig: default
                maxWaitTime: 750
            test2:
                maxConcurrentCalls: 100
                maxWaitDuration: PT1S
    threadPoolBulkhead:
        configs:
            default:
                threadPoolProperties:
                    maxThreadPoolSize: 4
                    coreThreadPoolSize: 2
                    queueCapacity: 2
                    keepAliveTime: 1000
            shared:
                threadPoolProperties:
                    maxThreadPoolSize: 4
                    coreThreadPoolSize: 2
                    queueCapacity: 2
                    keepAliveTime: 1000
        backends:
            test1:
                baseConfig: default
            test2:
                threadPoolProperties:
                    maxThreadPoolSize: 1
                    coreThreadPoolSize: 1
                    queueCapacity: 1
                    keepAliveDuration: PT1S